### ISSUE TITLE
HTML/CSS知识树总览

### ISSUE THREAD

**Issue by zhaobinglong** [zhaobinglong/myBlog#5]
## 盒子模型
- content-box (W3C 标准盒模型)，content-box是先根据设定的样式确定元素content的宽高，有border和padding的情况下再额外增加盒子的宽高，内容宽高不受影响，设定多少就是多少。
- border-box (IE 盒模型)，border-box是先根据设定的样式固定盒子的宽高，如果有border和padding的情况下，再根据盒子的宽高减去border或者padding，内容的宽高会受到影响，会被减去border或者padding。

## 盒子模型的转换
box-sizing: content-box|border-box|inherit;

content-box | 这是由 CSS2.1 规定的宽度高度行为。宽度和高度分别应用到元素的内容框。在宽度和高度之外绘制元素的内边距和边框。
-- | --
border-box | 为元素设定的宽度和高度决定了元素的边框盒。就是说，为元素指定的任何内边距和边框都将在已设定的宽度和高度内进行绘制。通过从已设定的宽度和高度分别减去边框和内边距才能得到内容的宽度和高度。
inherit | 规定应从父元素继承 box-sizing 属性的值。

**Comment by zhaobinglong** [comment]
## BFC
块级格式化上下文，是一个独立的渲染区域，让处于 BFC 内部的元素与外部的元素相互隔离，使内外元素的定位不会相互影响。

## 触发条件
- position: absolute/fixed
- display: inline-block / table
- float 元素
- ovevflow !== visible

## 应用
- margin重叠
- 元素浮动导致高度塌陷

**Comment by zhaobinglong** [comment]
## 居中布局通用解决方案和flex

**Comment by zhaobinglong** [comment]
## CSS3新增属性
border-radius
border-color
box-shadow
transform
animation


## 选择器优先级
!important > 行内样式 > #id > .class > tag > * > 继承 > 默认

## 解析方式
从右往左 解析，这里就涉及到web性能优化的一个知识点，就是写CSS的时候，要注意不能嵌套太深

**Comment by zhaobinglong** [comment]
## 去除浮动

- 通过增加尾元素清除浮动:after / <br> : clear: both
- 创建父级 BFC

## 脏属性【重要】
这是一个不应该这样使用属性，float属性存在的意义是为了设置文档中文字可以环绕图片布局，后来被滥用到了布局层面。不得不用这种hack手段来处理，这是不正确的，float不应该用在布局这里

**Comment by zhaobinglong** [comment]
## CSS预处理scss/less
```css
## sass处理css
// 能力一：定义变量，用$符号来定义
$blue : #1875e7;　
$highlight-color: #F90;

// 能力二： 计算属性
body {
  margin: (14px/2); top: 50px + 100px;
}

// 能力三：嵌套代码，
// 在Sass中，你可以像俄罗斯套娃那样在规则块中嵌套规则块
div {
  hi {
    color:red;
  }
}

// 能力四：利用mixin导入代码块
@mixin clearfix {
    width: 100px
  }
}
div {
  @include clearfix;
}

// 能力五：父选择器的标识符&;
article a {
  color: blue;
  &:hover { color: red }
}
>>>>
// 当包含父选择器标识符的嵌套规则被打开时，它不会像后代选择器那样进行拼接，而是&被父选择器直接替换：
article a { color: blue }
article a:hover { color: red }

// 能力6: 群组选择器嵌套
.container h1, .container h2, .container h3 { margin-bottom: .8em }
.container {
  h1, h2, h3 {margin-bottom: .8em}
}

// 能力7: 子组合选择器和同层组合选择器：>、+和~
// 你可以用子组合选择器>选择一个元素的直接子元素。下面的例子中，第一个选择器会选择article下的所有命中section选择器的元素。第二个选择器只会选择article下紧跟着的子元素中命中section选择器的元素。
article section { margin: 5px }
article > section { border: 1px solid #ccc }

// 能力8:嵌套属性
nav {
  border: {
  style: solid;
  width: 1px;
  color: #ccc;
  }
}
>>>>>>
nav {
  border-style: solid;
  border-width: 1px;
  border-color: #ccc;
}
                   
// 能力9: 混合气（将大块大块的重复样式提炼出来）
@mixin rounded-corners {
  -moz-border-radius: 5px;
  -webkit-border-radius: 5px;
  border-radius: 5px;
}
notice {
  background-color: green;
  border: 2px solid #00aa00;
  @include rounded-corners; // 在这里引用
}
                   
// 能能力10:使用选择器继承来精简CSS;

.error {
  border: 1px solid red;
  background-color: #fdd;
}
.seriousError {
  @extend .error;
  border-width: 3px;
}
                   
// module的能力
@import './common';


## less处理css

// 定义变量
@bk = '#000'
```

## 区别
Less是基于JavaScript，是在客户端处理的。Sass是基于Ruby的，是在服务器端处理的。（我在下载观摩一些开源项目的时候，经常遇到node-sass安装错误）
关于变量在Less和Sass中的唯一区别就是Less用@，Sass用$。
输出设置，Less没有输出设置，Sass提供4中输出选项：nested, compact, compressed 和 expanded。
Sass支持条件语句，可以使用if{}else{},for{}循环等等，而Less不支持。
