### ISSUE TITLE
web布局之居中

### ISSUE THREAD

**Issue by zhaobinglong** [zhaobinglong/myBlog#8]
## 参考
https://juejin.im/post/6844903679242305544

**Comment by zhaobinglong** [comment]
## 容器垂直居中
### flex布局居中
```css
.parent {
	display: flex;
	align-items: center;
	height: 500px;
	background-color: #EFEFEF;
}
.son {
	height: 200px;
	width: 200px;
	background-color: red;
}
```
### 绝对定位加位移居中
```css
	height: 500px;
	background-color: #EFEFEF;
	position: relative;
}
.son {
	position: absolute;
	transform: translate(0, -50%);
	top: 50%;
	height: 200px;
	width: 200px;
	background-color: red;
}
```

**Comment by zhaobinglong** [comment]
## 容器水平居中
### 利用auto居中
```css
.center-me {
  margin: 0 auto;
}
```

**Comment by zhaobinglong** [comment]
## 文字垂直居中
###   line-height居中
```css
.center-text-trick {
  height: 100px;
  line-height: 100px;
  white-space: nowrap;
}
```

**Comment by zhaobinglong** [comment]
## 文字水平居中
```css
.center{
  text-align: center;
}
```
