### ISSUE TITLE
css特殊场景下的解决方案

### ISSUE THREAD

**Issue by zhaobinglong** [zhaobinglong/myBlog#97]
## 多个容器堆叠在一起，边框不变粗
原理上是给父元素设置左边框和上边框，然后子元素统一设置右边框和下边框
## demo
```css
.father{
    width:400px;
}
.c{
    width:99px;/*此处有改动：（99+1）*4 = 400*/
    height:100px;
    float:left;
    border:1px solid black;
    border-left:none;
    border-top:none;
}
.father:after{
    display:block; 
    content:"clear";
    height:0; 
    clear:both;
    overflow:hidden; 
    visibility:hidden;
}
/*给父元素加border-top和border-left*/
.father{
    border-top:1px solid black;
    border-left:1px solid black;
}
```
